workflows:
  ios-workflow:
    name: iOS ESP OTA Updater
    instance_type: mac_mini_m1
    max_build_duration: 60
    working_directory: ESPOTAUpdater
    environment:
      vars:
        XCODE_WORKSPACE: "ESPOTAUpdater.xcworkspace"
        XCODE_SCHEME: "ESPOTAUpdater"
        BUNDLE_ID: "com.yourname.espotaupdater"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    # publishing bölümünü şimdilik kaldırdık

  android-workflow:
    name: Android ESP OTA Updater
    instance_type: linux_x2
    max_build_duration: 60
    working_directory: ESPOTAUpdater
    environment:
      vars:
        PACKAGE_NAME: "com.yourname.espotaupdater"
      node: 18.17.0
      java: 11
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - ESPOTAUpdater/android/app/build/outputs/**/*.apk
