workflows:
  ios-workflow:
    name: iOS ESP OTA Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    working_directory: ESPOTAUpdater
    environment:
      vars:
        XCODE_WORKSPACE: "ios/ESPOTAUpdater.xcworkspace"
        XCODE_SCHEME: "ESPOTAUpdater"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies with CLI 18.0.0
        script: |
          npm ci
          npm list @react-native-community/cli-platform-ios
      - name: Clean and prepare iOS
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update --verbose
      - name: Build iOS for Simulator
        script: |
          xcodebuild build \
            -workspace "ios/ESPOTAUpdater.xcworkspace" \
            -scheme "ESPOTAUpdater" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=18.0' \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -verbose
    artifacts:
      - ios/build/Build/Products/Debug-iphonesimulator/*.app
      - /tmp/xcodebuild_logs/*.log
