workflows:
  ios-workflow:
    name: iOS ESP OTA Updater
    instance_type: mac_mini_m1
    max_build_duration: 60
    working_directory: ESPOTAUpdater
    environment:
      vars:
        XCODE_WORKSPACE: "ios/ESPOTAUpdater.xcworkspace"
        XCODE_SCHEME: "ESPOTAUpdater"
        BUNDLE_ID: "com.ismailozturk.espotaupdater"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --workspace "ios/ESPOTAUpdater.xcworkspace" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist "export_options.plist"
    artifacts:
      - build/ios/ipa/*.ipa
