name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'ESPOTAUpdater/package-lock.json'  # Bu satırı ekleyin

        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install npm dependencies
      run: |
        cd ESPOTAUpdater
        npm install
        
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
      with:
        gradle-wrapper-directory: ESPOTAUpdater/android
        
    - name: Make gradlew executable
      run: |
        cd ESPOTAUpdater/android
        chmod +x gradlew
        
    - name: Build Android APK
      run: |
        cd ESPOTAUpdater/android
        ./gradlew assembleDebug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: esp-ota-updater-debug
        path: ESPOTAUpdater/android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ESPOTAUpdater/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('ESPOTAUpdater/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
